"""Extracts text content from real PDF files (born-digital, i.e. the PDF has an
actual text layer - most EOBs generated by a payer system, not a scanned image).

Scanned/image-only PDFs have no text layer and will extract empty/near-empty
text - that case would need OCR, which is out of scope here; callers should
treat an empty result as "could not read this PDF" and fall back accordingly.
"""
import io

from pypdf import PdfReader


def extract_text(pdf_bytes: bytes) -> str:
    reader = PdfReader(io.BytesIO(pdf_bytes))
    pages_text = [page.extract_text() or "" for page in reader.pages]
    return "\n".join(pages_text).strip()
